### ISSUE TITLE
Cannot put data into elasticsearch

### ISSUE THREAD

**Issue by tymofii-polekhin** [mesos/elasticsearch#144]
Hello,
i've cloned this repo and used guide to build scheduler and executor jar's, then created docker images using `Dockerfile` from this repo.

The cluster seems to be operational, but i cant put any data into it. Here is the output:
```
[centos@host-01 ~]$ curl -XGET "http://localhost:8082/_cluster/health"
{
    "cluster_name":"mesos-elasticsearch",
    "status":"green",
    "timed_out":false,
    "number_of_nodes":6,
    "number_of_data_nodes":6,
    "active_primary_shards":0,
    "active_shards":0,
    "relocating_shards":0,
    "initializing_shards":0,
    "unassigned_shards":0
}
```
```
[centos@host-01 ~]$ curl 'http://localhost:8082/?pretty'
{
  "status" : 200,
  "name" : "Eugene Judd",
  "cluster_name" : "mesos-elasticsearch",
  "version" : {
    "number" : "1.4.5",
    "build_hash" : "2aaf797f2a571dcb779a3b61180afe8390ab61f9",
    "build_timestamp" : "2015-04-27T08:06:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I've tried with curl:
```
[centos@host-01 ~]$ curl -XPUT "http://localhost:8082/index/type/1" -d'{"title":"Mad Max","year":"2015"}'
{
    "error":"RemoteTransportException[[Agon][inet[/10.0.0.3:5053]][indices:admin/create]]; 
        nested: IndexCreationException[[index] failed to create index]; 
        nested: NoClassDefFoundError[Could not initialize class org.elasticsearch.index.codec.postingsformat.PostingFormats]; ",
    "status":500
}
```
And then with python driver:
```
[centos@host-01 ~]$ pip install elasticsearch
[centos@host-01 ~]$ python
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch(['http://localhost:8082'])
>>> es.index(index="my-index", doc_type="test-type", id=42, body={"any": "data", "timestamp": "now"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 254, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, u'RemoteTransportException[[Agon][inet[/10.0.0.3:5053]][indices:admin/create]]; 
    nested: IndexCreationException[[my-index] failed to create index]; 
    nested: NoClassDefFoundError[Could not initialize class org.elasticsearch.index.codec.postingsformat.PostingFormats]; ')
```

Can you help me understand what is the root of the problem? Thanks!

**Comment by Y4Rv1K** [comment]
+1 We are facing with the same issue.

**Comment by tymofii-polekhin** [comment]
After today commits:
fa05a711c36f40f37a2925f2351f442a92af633f
59559ab039324322a9c39114ee513d0c8f5a8dcc

I've rebuilded the package and now the problem seems to be gone!
```
curl -XPUT "http://es-master-node:3889/movies/movie/1" -d'{"name":"MadMax","year":"2015"}'
{"_index":"movies","_type":"movie","_id":"1","_version":1,"created":true}
```

```
curl -XGET "http://es-master-node:3889/movies/movie/1"
{"_index":"movies","_type":"movie","_id":"1","_version":1,"found":true,"_source":{"name":"MadMax","year":"2015"}}
```

**Comment by frankscholten** [comment]
Fixed by https://github.com/mesos/elasticsearch/commit/fa05a711c36f40f37a2925f2351f442a92af633f
