### ISSUE TITLE
Scheduler web UI fails to load because it "Failed to instantiate module mesos-es-ui"

### ISSUE THREAD

**Issue by jhftrifork** [mesos/elasticsearch#329]
## Steps to reproduce

1. Check out [current master](https://github.com/mesos/elasticsearch/tree/61b475295ed461ed1a6b92a2966844b6767832a4)
2. `./gradlew build system-test:main`
3. Open `http://172.17.0.XX:31100`

## Expected behavior

Web UI loads

## Actual behavior

Web UI stops loading at blank page; error in console:

```
Failed to instantiate module mesos-es-ui due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=h...)
    at Error (native)
    at http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:6:416
    at http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:38:15
    at n (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:7:322)
    at g (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:37:92)
    at http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:37:261
    at n (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:7:322)
    at g (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:37:92)
    at db (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:40:367)
    at d (http://172.17.0.49:31100/webjars/angularjs/1.4.1/angular.min.js:19:219
```

**Comment by jhftrifork** [comment]
Also broken in `1f06fe5`

**Comment by jhftrifork** [comment]
Not broken in `7525fa1`

**Comment by jhftrifork** [comment]
Broken in `cade114`

**Comment by jrslv** [comment]
Cannot reproduce following the steps above.

**Comment by mwl** [comment]
Unable to reproduce
