### ISSUE TITLE
Gradle release method crashes

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#389]
The changes to the build.gradle in #360 killed the release. I have reverted back to before your commit to work.
```
$ gw release -PreleaseType=patch -PuserName=philwinder --stacktrace
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.3/userguide/gradle_daemon.html.
Current version: 0.5.0
Next version: 0.5.1

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':commons:publish'.
> Task with path 'publishDockerImageWithVersion' not found in project ':commons'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Could not determine the dependencies of task ':commons:publish'.
    at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
    at ...
Caused by: org.gradle.api.UnknownTaskException: Task with path 'publishDockerImageWithVersion' not found in project ':commons'.
    at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:150)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.resolveTask(DefaultTaskContainer.java:144)
    at org.gradle.api.internal.tasks.DefaultTaskDependency.resolve(DefaultTaskDependency.java:80)
    at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:86)
    at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:200)
    at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
    at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
    at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:74)
    at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:63)
    ... 49 more


BUILD FAILED

Total time: 8.279 secs

**Comment by jrslv** [comment]
@philwinder is there a way how to reproduce this without doing an actual release?

**Comment by philwinder** [comment]
You'd have to setup a new test repository with this code. I would have thought you would have done this to test. ;-)

**Comment by jrslv** [comment]
Oh yes, I'm using my fork, I was just wondering. But still I can't reproduce this bug. When I apply changes from https://github.com/mesos/elasticsearch/pull/360/files to current master branch, I'm getting the following, i.e. `:scheduler:publishDockerImageWithVersion` is found and applied:

```
...
:scheduler:tagDockerImageWithVersion
Tagging image with ID 'mesos/elasticsearch-scheduler'.
:scheduler:publishDockerImageWithVersion
Pushing image with name 'mesos/elasticsearch-scheduler'.
...
```

Commands:

```
./gradlew clean build
./gradlew release -PreleaseType=patch -PuserName=jrslv --stacktrace
```

But maybe I'm doing something different than you do, I've never did an actual release before. Have you maybe got any idea what could be the catch?

**Comment by philwinder** [comment]
It now appears to be no longer an issue. Everything worked fine on this release.
