### ISSUE TITLE
ZooKeeper: bad arguments

### ISSUE THREAD

**Issue by commarmi76** [mesos/elasticsearch#409]
Hello,

I'm testing version 0.6.0 with docker, and there is an error:
--container="mesos-87d59906-c49b-4993-af51-55374d09820a-S1.a0916665-35ed-444a-9c98-36c591dc43f3" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/tmp/mesos/slaves/87d59906-c49b-4993-af51-55374d09820a-S1/frameworks/87d59906-c49b-4993-af51-55374d09820a-0000/executors/elasticsearch-mesos-scheduler.2ceae95c-8d0a-11e5-9c00-525400a837fc/runs/a0916665-35ed-444a-9c98-36c591dc43f3" --stop_timeout="0ns"
--container="mesos-87d59906-c49b-4993-af51-55374d09820a-S1.a0916665-35ed-444a-9c98-36c591dc43f3" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/tmp/mesos/slaves/87d59906-c49b-4993-af51-55374d09820a-S1/frameworks/87d59906-c49b-4993-af51-55374d09820a-0000/executors/elasticsearch-mesos-scheduler.2ceae95c-8d0a-11e5-9c00-525400a837fc/runs/a0916665-35ed-444a-9c98-36c591dc43f3" --stop_timeout="0ns"
Registered docker executor on cloud13.scytl.net
Starting task elasticsearch-mesos-scheduler.2ceae95c-8d0a-11e5-9c00-525400a837fc
[INFO] 2015-11-17 09:04:17,288 org.apache.mesos.elasticsearch.scheduler.Configuration getMesosStateZKURL - Zookeeper framework option is blank, using Zookeeper for Mesos: zk://192.168.0.183:2181/mesos
[DEBUG] 2015-11-17 09:04:17,496 org.apache.mesos.elasticsearch.scheduler.FrameworkInfoFactory setWebuiUrl - Setting webuiUrl to http://8b912bc40304:31100
[INFO] 2015-11-17 09:04:17,930 org.apache.mesos.elasticsearch.scheduler.Main logStarting - Starting Main v0.5.2 on 8b912bc40304 with PID 6 (/tmp/elasticsearch-mesos-scheduler.jar started by root in /)
[DEBUG] 2015-11-17 09:04:17,930 org.apache.mesos.elasticsearch.scheduler.Main logStarting - Running with Spring Boot v0.5.2, Spring v0.5.2
[DEBUG] 2015-11-17 09:04:18,946 org.jboss.logging make - Logging Provider: org.jboss.logging.Log4jLoggerProvider
[INFO] 2015-11-17 09:04:18,947 org.hibernate.validator.internal.util.Version <clinit> - HV000001: Hibernate Validator 5.1.3.Final
[DEBUG] 2015-11-17 09:04:18,963 org.hibernate.validator.internal.engine.resolver.DefaultTraversableResolver detectJPA - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
[DEBUG] 2015-11-17 09:04:18,975 org.hibernate.validator.internal.engine.ConfigurationImpl messageInterpolator - Setting custom MessageInterpolator of type org.springframework.validation.beanvalidation.LocaleContextMessageInterpolator
[DEBUG] 2015-11-17 09:04:18,975 org.hibernate.validator.internal.engine.ConfigurationImpl constraintValidatorFactory - Setting custom ConstraintValidatorFactory of type org.springframework.validation.beanvalidation.SpringConstraintValidatorFactory
[DEBUG] 2015-11-17 09:04:18,978 org.hibernate.validator.internal.engine.ConfigurationImpl parameterNameProvider - Setting custom ParameterNameProvider of type com.sun.proxy.$Proxy25
[DEBUG] 2015-11-17 09:04:18,989 org.hibernate.validator.internal.xml.ValidationXmlParser getInputStream - Trying to load META-INF/validation.xml for XML based Validator configuration.
[DEBUG] 2015-11-17 09:04:18,999 org.hibernate.validator.internal.xml.ValidationXmlParser getInputStream - No META-INF/validation.xml found. Using annotation based configuration only.
[INFO] 2015-11-17 09:04:19,724 org.apache.catalina.core.StandardService log - Starting service Tomcat
[INFO] 2015-11-17 09:04:19,725 org.apache.catalina.core.StandardEngine log - Starting Servlet Engine: Apache Tomcat/8.0.23
[INFO] 2015-11-17 09:04:19,926 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] log - Initializing Spring embedded WebApplicationContext
[DEBUG] 2015-11-17 09:04:21,105 org.hibernate.validator.internal.engine.resolver.DefaultTraversableResolver detectJPA - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
[DEBUG] 2015-11-17 09:04:21,106 org.hibernate.validator.internal.engine.ConfigurationImpl messageInterpolator - Setting custom MessageInterpolator of type org.springframework.validation.beanvalidation.LocaleContextMessageInterpolator
[DEBUG] 2015-11-17 09:04:21,106 org.hibernate.validator.internal.engine.ConfigurationImpl constraintValidatorFactory - Setting custom ConstraintValidatorFactory of type org.springframework.validation.beanvalidation.SpringConstraintValidatorFactory
[DEBUG] 2015-11-17 09:04:21,106 org.hibernate.validator.internal.engine.ConfigurationImpl parameterNameProvider - Setting custom ParameterNameProvider of type com.sun.proxy.$Proxy25
[DEBUG] 2015-11-17 09:04:21,108 org.hibernate.validator.internal.xml.ValidationXmlParser getInputStream - Trying to load META-INF/validation.xml for XML based Validator configuration.
[DEBUG] 2015-11-17 09:04:21,109 org.hibernate.validator.internal.xml.ValidationXmlParser getInputStream - No META-INF/validation.xml found. Using annotation based configuration only.
[INFO] 2015-11-17 09:04:21,405 org.apache.coyote.http11.Http11NioProtocol log - Initializing ProtocolHandler ["http-nio-31100"]
[INFO] 2015-11-17 09:04:21,415 org.apache.coyote.http11.Http11NioProtocol log - Starting ProtocolHandler ["http-nio-31100"]
[INFO] 2015-11-17 09:04:21,422 org.apache.tomcat.util.net.NioSelectorPool log - Using a shared selector for servlet write/read
[INFO] 2015-11-17 09:04:21,439 org.apache.mesos.elasticsearch.scheduler.Main logStarted - Started Main in 3.805 seconds (JVM running for 5.59)
[INFO] 2015-11-17 09:04:21,439 org.apache.mesos.elasticsearch.scheduler.Configuration getFrameworkZKURL - Zookeeper framework option is blank, using Zookeeper for Mesos: zk://192.168.0.183:2181/mesos
[INFO] 2015-11-17 09:04:21,439 class org.apache.mesos.elasticsearch.scheduler.ElasticsearchScheduler run - Starting ElasticSearch on Mesos - [numHwNodes: 3, zk mesos: zk://192.168.0.183:2181/mesos, zk framework: 192.168.0.183:2181, ram:256.0]
[INFO] 2015-11-17 09:05:13,581 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] log - Initializing Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2015-11-17 09:05:13,998 org.apache.mesos.elasticsearch.scheduler.state.ClusterState getTaskList - Unable to get key for cluster state due to invalid frameworkID.
java.io.IOException: Unable to get zNode
	at org.apache.mesos.elasticsearch.scheduler.state.SerializableZookeeperState.get(SerializableZookeeperState.java:51)
	at org.apache.mesos.elasticsearch.scheduler.state.ClusterState.getTaskList(ClusterState.java:44)
	at org.apache.mesos.elasticsearch.scheduler.state.ClusterState.getGuiTaskList(ClusterState.java:57)
	at org.apache.mesos.elasticsearch.scheduler.ElasticsearchScheduler.getTasks(ElasticsearchScheduler.java:42)
	at org.apache.mesos.elasticsearch.scheduler.controllers.TasksController.getTasks(TasksController.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: Failed to get '/elasticsearch/mesos-ha//stateList' in ZooKeeper: bad arguments
	at org.apache.mesos.state.AbstractState$FetchFuture.get(Native Method)
	at org.apache.mesos.state.AbstractState$FetchFuture.get(AbstractState.java:226)
	at org.apache.mesos.elasticsearch.scheduler.state.SerializableZookeeperState.get(SerializableZookeeperState.java:29)
	... 49 more

Do you know what is the problem ?

**Comment by philwinder** [comment]
Hi, that is because elasticsearxh couldn't register as a framework with your mesos cluster for some reason.
The actual error is that the web ui is trying to retrieve cluster information, via the framework is, but the framework I'd doesn't exist because it hasn't registered.
I'll open a bug to suppress this error message.
In the mean time, you need to debug to find out why it can't register as a framework. Things too look at:
- Auth/Roles
- Old framework state in zookeeper (remove if there is any)
- Something wrong with the mesos setup.

Thanks,
Phil

**Comment by philwinder** [comment]
See #410

**Comment by commarmi76** [comment]
I think the problem is with the IPs again. Apparently mesos-master is trying to send acknowledgement to the docker internal IP(172.17.0.1). If the mesos-master and the docker image are running in the same machine there aren't any problem.

994 master.cpp:2260] Framework 87d59906-c49b-4993-af51-55374d09820a-0003 (elasticsearch) at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102 already subscribed, resending acknowledgement
W1117 15:16:28.477484 31994 master.hpp:1532] Master attempted to send message to disconnected framework 87d59906-c49b-4993-af51-55374d09820a-0003 (elasticsearch) at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102
I1117 15:16:30.719002 31986 master.cpp:4967] Sending 1 offers to framework 87d59906-c49b-4993-af51-55374d09820a-0000 (marathon) at scheduler-ad472422-231d-42e7-8327-5e1a60a9f3d0@192.168.0.183:62726
I1117 15:16:30.721359 31998 master.cpp:2918] Processing ACCEPT call for offers: [ 87d59906-c49b-4993-af51-55374d09820a-O1219 ] on slave 87d59906-c49b-4993-af51-55374d09820a-S0 at slave(1)@192.168.0.191:5051 (cloud12.scytl.net) for framework 87d59906-c49b-4993-af51-55374d09820a-0000 (marathon) at scheduler-ad472422-231d-42e7-8327-5e1a60a9f3d0@192.168.0.183:62726
I1117 15:16:30.721701 31996 hierarchical.hpp:1103] Recovered cpus(*):15.8; mem(*):16353; disk(*):1279; ports(*):[31000-31861, 31863-32000] (total: cpus(*):16; mem(*):16865; disk(*):1279; ports(*):[31000-32000], allocated: cpus(*):0.2; mem(*):512; ports(*):[31862-31862]) on slave 87d59906-c49b-4993-af51-55374d09820a-S0 from framework 87d59906-c49b-4993-af51-55374d09820a-0000
I1117 15:16:35.870769 31998 http.cpp:336] HTTP GET for /master/state.json from 10.0.96.100:34729 with User-Agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36'
I1117 15:16:40.289532 31996 master.cpp:2179] Received SUBSCRIBE call for framework 'elasticsearch' at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102
I1117 15:16:40.289782 31996 master.cpp:2250] Subscribing framework elasticsearch with checkpointing enabled and capabilities [  ]
I1117 15:16:40.289798 31996 master.cpp:2260] Framework 87d59906-c49b-4993-af51-55374d09820a-0003 (elasticsearch) at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102 already subscribed, resending acknowledgement
W1117 15:16:40.289818 31996 master.hpp:1532] Master attempted to send message to disconnected framework 87d59906-c49b-4993-af51-55374d09820a-0003 (elasticsearch) at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102
E1117 15:16:41.375360 32001 socket.hpp:174] Shutdown failed on fd=33: Transport endpoint is not connected [107]
I1117 15:16:45.877652 31991 http.cpp:336] HTTP GET for /master/state.json from 10.0.96.100:34729 with User-Agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36'
I1117 15:16:52.106884 31992 master.cpp:2179] Received SUBSCRIBE call for framework 'elasticsearch' at scheduler-ea0fb395-2fe6-48a3-9ab2-df2935d181d2@172.17.0.1:24102
I1117 15:16:52.107216 31992 master.cpp:2250] Subscribing framework elasticsearch with checkpointing enabled and capabilities [  ]

**Comment by commarmi76** [comment]
I puted a static route in the mesos-master machine and now all works well.
I don't know why other people haven't problems with the network.

**Comment by philwinder** [comment]
Ok, you didn't mention you were using MiniMesos. In the documentation and on the MiniMesos site, we provide instructions on how to add a route.

Thanks anyway.

**Comment by commarmi76** [comment]
I am not using MiniMesos.

**Comment by philwinder** [comment]
Sorry commarmi76, I got mixed up. Yes, I know what you mean. But with capability comes great complexity. It's our job to try and make the process as seamless as possible and the stack trace above doesn't help when it is caused by another part of the system.

Thanks for helping us make it better.

Phil

**Comment by heww** [comment]
I have the same problem deployed using marathon. As @commarmi76 said that it's ip problem, then I launch scheduler docker using host net, it works.

**Comment by philwinder** [comment]
Yes, that's potentially a dns problem on your cluster. The scheduler container needs to be resolveable by the master. If you're in bridge mode, it will be given a hostname that is equal to the docker container id. If that is not resolvable, then it won't be able to communicate.

So generally, the solution is provide a service discovery mechanism, or run in host mode so the scheduler is assigned the same hostname as the slave/agent machine.

**Comment by heww** [comment]
I think this should be mentioned in docs.

**Comment by philwinder** [comment]
Yes, I agree. I'll add a task. Thanks!
