### ISSUE TITLE
Failed to load native Mesos library from /usr/lib/libmesos-0.24.1.so

### ISSUE THREAD

**Issue by canadatom** [mesos/elasticsearch#422]
Here is my marathon json
```json
{
  "id": "elasticsearch-mesos-scheduler",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler",
      "network": "HOST"
    }
  },
  "args": ["--zookeeperMesosUrl", "zk://node-1:2181,node-2:2181,node-3:2181/mesos"],
  "cpus": 2,
  "mem": 1024.0,
  "env": {
    "JAVA_OPTS": "-Xms256m -Xmx1024m"
  },
  "instances": 1
}

```

This is from executor from elasticsearch-scheduler
```
Warning: '-c' is deprecated, it will be replaced by '--cpu-shares' soon. See usage.
Failed to load native Mesos library from /usr/lib/libmesos-0.24.1.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/libmesos-0.24.1.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:188)
	at org.apache.mesos.MesosExecutorDriver.<clinit>(MesosExecutorDriver.java:52)
	at org.apache.mesos.elasticsearch.executor.Main.main(Main.java:22)
```
The following logs is from schedule log
```
I1215 14:53:08.507387   588 exec.cpp:133] Version: 0.24.1
I1215 14:53:08.512552   589 exec.cpp:207] Executor registered on slave 20151215-143223-1750233610-5050-1-S3
Warning: '-c' is deprecated, it will be replaced by '--cpu-shares' soon. See usage.
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@716: Client environment:host.name=OCLD1LX-MESOS-S2
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.3.1.el7.x86_64
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Wed Dec 9 14:09:15 UTC 2015
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-12-15 14:53:09,640:6(0x7fa3e8db0700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=node-1:2181,node-2:2181,node-3:2181 sessionTimeout=20000 watcher=0x7fa41e528600 sessionId=0 sessionPasswd=<null> context=0x7fa3d4001c20 flags=0
2015-12-15 14:53:09,641:6(0x7fa3e75ad700):ZOO_INFO@check_events@1703: initiated connection to server [10.114.82.117:2181]
2015-12-15 14:53:09,644:6(0x7fa3e75ad700):ZOO_INFO@check_events@1750: session establishment complete on server [10.114.82.117:2181], sessionId=0x351a616af790003, negotiated timeout=20000
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tmp/elasticsearch-mesos-scheduler.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/elasticsearch-mesos-scheduler.jar!/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2015-12-15 14:53:18,295:6(0x7fa3eb5b5700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-12-15 14:53:18,295:6(0x7fa3eb5b5700):ZOO_INFO@log_env@716: Client environment:host.name=OCLD1LX-MESOS-S2
2015-12-15 14:53:18,295:6(0x7fa3eb5b5700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-12-15 14:53:18,295:6(0x7fa3eb5b5700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.3.1.el7.x86_64
2015-12-15 14:53:18,295:6(0x7fa3eb5b5700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Wed Dec 9 14:09:15 UTC 2015
2015-12-15 14:53:18,296:6(0x7fa3eb5b5700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-12-15 14:53:18,296:6(0x7fa3eb5b5700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-12-15 14:53:18,296:6(0x7fa3eb5b5700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-12-15 14:53:18,296:6(0x7fa3eb5b5700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=node-1:2181,node-2:2181,node-3:2181 sessionTimeout=10000 watcher=0x7fa41e528600 sessionId=0 sessionPasswd=<null> context=0x7fa3dc001600 flags=0
I1215 14:53:18.298959    21 sched.cpp:164] Version: 0.25.0
2015-12-15 14:53:18,302:6(0x7fa3c0ffe700):ZOO_INFO@check_events@1703: initiated connection to server [10.114.82.117:2181]
2015-12-15 14:53:18,305:6(0x7fa3c0ffe700):ZOO_INFO@check_events@1750: session establishment complete on server [10.114.82.117:2181], sessionId=0x351a616af790004, negotiated timeout=10000
I1215 14:53:18.305372    28 group.cpp:331] Group process (group(1)@10.114.49.173:32964) connected to ZooKeeper
I1215 14:53:18.305411    28 group.cpp:805] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1215 14:53:18.305423    28 group.cpp:403] Trying to create path '/mesos' in ZooKeeper
I1215 14:53:18.308210    28 detector.cpp:156] Detected a new leader: (id='25')
I1215 14:53:18.308310    28 group.cpp:674] Trying to get '/mesos/json.info_0000000025' in ZooKeeper
I1215 14:53:18.309289    28 detector.cpp:481] A new leading master (UPID=master@10.114.82.104:5050) is detected
I1215 14:53:18.309355    28 sched.cpp:262] New master detected at master@10.114.82.104:5050
I1215 14:53:18.309535    28 sched.cpp:272] No credentials provided. Attempting to register without authentication
I1215 14:53:18.313165    28 sched.cpp:641] Framework registered with 20151215-143223-1750233610-5050-1-0000
```

**Comment by jgarcia-mesosphere** [comment]
Looks to me like the Docker container is not mounting the `/opt/mesosphere` folder in the case of DCOS, else is getting the wrong env var:

```
Failed to load native Mesos library from /opt/mesosphere/packages/mesos--52cbecde74638029c3ba0ac5e5ab81df8debf0fa/lib/libmesos-0.25.0.so
```

```
    "Mounts": [
        {
            "Source": "/var/lib/mesos/slave/elasticsearch",
            "Destination": "/data",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/var/lib/mesos/slave/slaves/fe10c27c-d365-4cdf-a1ae-f6a5c8d455be-S4/frameworks/fe10c27c-d365-4cdf-a1ae-f6a5c8d455be-0003/executors/500b7272-5890-4fcd-99f3-a40c1789877c/runs/3c342120
-6fdb-46b9-aa98-7af4842a132c",
            "Destination": "/mnt/mesos/sandbox",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/tmp/config",
            "Destination": "/tmp/config",
            "Mode": "ro",
            "RW": false
        }
    ],
```

**Comment by philwinder** [comment]
@canadatom @jgarcia-mesosphere 
Short story: Mesos Elasticsearch is built against 0.25.0, not 0.24. Please upgrade your Mesos.

Long story: Our docker files install Mesos.
https://github.com/mesos/elasticsearch/blob/master/commons/Dockerfile#L12

So the Mesos libraries are preinstalled in the container, they are not from your system. The code reads the libray from this location: https://github.com/mesos/elasticsearch/blob/master/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/configuration/ExecutorEnvironmentalVariables.java#L14

We do this because, in our experience, Mesos is not backwards compatible. (Mainly due to the protocol buffers).

If you consider the mounting of your host's Mesos libraries a useful feature, please open a new issue with that feature request.

Thanks!

**Comment by jgarcia-mesosphere** [comment]
For what it's worth, I encountered this error on `0.25.0`. It seems like I was inadvertently overwriting an env variable that should point to the `libmesos` in the container and pointing it to libmesos on the host, i.e. not in the container and not accessible to ELS.
Should be obsoleted by #466 .

**Comment by brndnmtthws** [comment]
I hacked together a workaround here:

https://github.com/brndnmtthws/elasticsearch/commit/fdaf22691586270a13b661bb6d1d55e0f9757edc

**Comment by philwinder** [comment]
Guys,
The library is provided inside the container. There is an env var, set by the code, which points to the file in the container. Please do not override the env var. Because the container doesn't have access to your host's filesystem, it won't be able to find your library.

**Comment by brndnmtthws** [comment]
Indeed, but the problem remains because the system-level environment variable takes precedence over the task-level env var.
