### ISSUE TITLE
Add null check around resource values

### ISSUE THREAD

**Issue by ryane** [mesos/elasticsearch#513]
```
I0223 20:11:53.531283 11561 sched.cpp:407] Successfully authenticated with master master@10.0.0.5:15050
I0223 20:11:53.535822 11561 sched.cpp:641] Framework registered with b60b6092-e153-47ab-a95c-c4d337357429-0003
Exception in thread "Thread-7" java.lang.NullPointerException
	at org.apache.mesos.elasticsearch.scheduler.ResourceCheck.isEnough(ResourceCheck.java:28)
	at org.apache.mesos.elasticsearch.scheduler.OfferStrategy.isEnoughCPU(OfferStrategy.java:101)
	at org.apache.mesos.elasticsearch.scheduler.OfferStrategy.lambda$new$21(OfferStrategy.java:29)
	at org.apache.mesos.elasticsearch.scheduler.OfferStrategy.lambda$evaluate$24(OfferStrategy.java:56)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.apache.mesos.elasticsearch.scheduler.OfferStrategy.evaluate(OfferStrategy.java:56)
	at org.apache.mesos.elasticsearch.scheduler.ElasticsearchScheduler.resourceOffers(ElasticsearchScheduler.java:93)
I0223 20:11:53.746459 11561 sched.cpp:1805] Asked to abort the driver
I0223 20:11:53.746608 11561 sched.cpp:1070] Aborting framework 'b60b6092-e153-47ab-a95c-c4d337357429-0003'
```

This is with the 0.7.1 version of the framework deployed via the ELK addon on Mantl 1.0.2 on Google Cloud. Any ideas?

**Comment by ryane** [comment]
reproduced with 0.7.2 as well.

**Comment by philwinder** [comment]
Ryan, thanks for the report. This is the line that is producing the null:
```
        return resource.getScalar().getValue() >= requiredValue;
```
The resource is received from Mesos. So I can only suspect that for some reason Mesos isn't providing the resource value properly. We've never seen this problem before, so I suspect its something to do with your setup. Is one of your machines special? Does it have no available resources or something?

Ah interesting, the scalar value is only optional: https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L572.

So I suspect it is one of your slaves that doesn't have any resources. We may need to put some safeguards around this.

Can I confirm that you are using Mesos 0.25.0?

**Comment by ryane** [comment]
Yes, this seems to be an edge case around cluster sizing. It does appear that this will occur if one of the nodes is at capacity in the cluster (CPU in this case). I've deployed the same code on clusters that have worker nodes with more resources without issue. And, yes, this is on Mesos 0.25.0.

**Comment by philwinder** [comment]
Cracking. Thanks for finding this. Again, something unexpected from Mesos. When there are no resources left, it doesn't set the resource to zero, it just doesn't set it.

I'll add some tests and fix.
