### ISSUE TITLE
Problems installing via Marathon Web UI

### ISSUE THREAD

**Issue by mongrelion** [mesos/elasticsearch#555]
On a fresh Mesos+Marathon installation (using the JSON installation method suggested in the official documentation https://mesos-elasticsearch.readthedocs.org/en/latest/#how-to-install-on-marathon)
I ran into the following issue:
```
I0415 15:11:53.163620  5428 exec.cpp:143] Version: 0.28.1
I0415 15:11:53.170949  5439 exec.cpp:217] Executor registered on slave c5278d5d-1f26-4996-b89d-3b6c1edc8e45-S1
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@716: Client environment:host.name=dcos-agent-003
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@724: Client environment:os.arch=4.5.0-1.el7.elrepo.x86_64
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Mon Mar 14 10:24:58 EDT 2016
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2016-04-15 15:11:54,535:1(0x7f98b73a7700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=1.2.3.4:2181 sessionTimeout=20000 watcher=0x7f98ee213600 sessionId=0 sessionPasswd=<null> context=0x7f98a4000cb0 flags=0
2016-04-15 15:11:54,540:1(0x7f98aeffd700):ZOO_INFO@check_events@1703: initiated connection to server [1.2.3.4:2181]
2016-04-15 15:11:54,581:1(0x7f98aeffd700):ZOO_INFO@check_events@1750: session establishment complete on server [1.2.3.4:2181], sessionId=0x1541a61c0850000, negotiated timeout=20000
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to bind to local host.
	at org.apache.mesos.elasticsearch.common.util.NetworkUtils.hostAddress(NetworkUtils.java:33)
	at org.apache.mesos.elasticsearch.common.util.NetworkUtils.hostSocket(NetworkUtils.java:38)
	at org.apache.mesos.elasticsearch.scheduler.Configuration.webUiAddress(Configuration.java:262)
	at org.apache.mesos.elasticsearch.scheduler.FrameworkInfoFactory.setWebuiUrl(FrameworkInfoFactory.java:52)
	at org.apache.mesos.elasticsearch.scheduler.FrameworkInfoFactory.getBuilder(FrameworkInfoFactory.java:29)
	at org.apache.mesos.elasticsearch.scheduler.Main.run(Main.java:62)
	at org.apache.mesos.elasticsearch.scheduler.Main.main(Main.java:30)
	... 6 more
```

This is the config JSON file I used for it:
```
{
  "id": "elasticsearch",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler",
      "network": "HOST"
    }
  },
  "args": ["--zookeeperMesosUrl", "zk://ZOOKEEPER_IP_ADDRESS:2181/mesos"],
  "cpus": 0.2,
  "mem": 512.0,
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "instances": 1
}
```
And I replaced the `ZOOKEEPER_IP_ADDRESS` with the IP of my ZooKeeper instance, of course.

**Comment by philwinder** [comment]
Hi Carlos. 
For some reason it was
'Unable to bind to local host.'

Not a framework issue but an infra one. It must be something to do with the way you have set up the host/Mesos. Maybe with the wrong permissions, or wrong libprocess ip or something. 

Try to get a simple we app working in host mode first.
